### PR TITLE
needs cstruct.ppx

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
looks like xentropyd -- not used by anyone i believe -- still relies on cstruct.syntax.. I opened https://github.com/ocaml/opam-repository/pull/6456 to reflect that (and once that merged, this one should be fine)

**Comment by hannesm** [comment]
now that xentropyd in opam-repo is fixed, travis is happy here \o/

**Comment by hannesm** [comment]
would be great to get this merged @djs55

**Comment by djs55** [comment]
Thanks!

**Pull request merged**
